# Generated by Django 4.1.4 on 2023-04-17 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0017_alter_channel_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, editable=False, max_length=32, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('visibility', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='pr', max_length=2)),
                ('is_updated', models.BooleanField(default=False)),
                ('allow_comment', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('music', models.FileField(upload_to='musics/user_music/')),
                ('thumbnail', models.ImageField(default='assets/images/default-music-thumbnail.jpg', upload_to='musics/thumbnail/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
