# Generated by Django 4.1.4 on 2023-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0002_subscription"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_subscription"
            ),
        ),
    ]
