# Generated by Django 4.1.4 on 2023-07-15 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0004_alter_membership_token_alter_subscription_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
