# Generated by Django 4.1.4 on 2023-01-08 09:48

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_token_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default=accounts.utils.user_id_generator, max_length=15),
        ),
    ]
