# Generated by Django 4.1.4 on 2023-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
