version: '3.9'

services:

  backend:

    extends:
      file: backend/docker-compose.yml
      service: backend

  postgres:
    extends:
      file: backend/docker-compose.yml
      service: postgres

  test_postgres:
    extends:
      file: backend/docker-compose.yml
      service: test_postgres

  pgadmin:
    extends:
      file: backend/docker-compose.yml
      service: pgadmin

  redis:
    extends:
      file: backend/docker-compose.yml
      service: redis

  flower:
    extends:
      file: backend/docker-compose.yml
      service: flower

  smtp4dev:
    extends:
      file: backend/docker-compose.yml
      service: smtp4dev

  celery:
    extends:
      file: backend/docker-compose.yml
      service: celery

  celery-beat:
    extends:
      file: backend/docker-compose.yml
      service: celery-beat


  # frontend:
  #   extends:
  #     file: frontend/docker-compose.yml
  #     service: frontend

volumes:
  postgres-data: