version: '3.9'

x-environment: &COMMON_VARS
    DJANGO_SETTINGS_MODULE: 'config.settings.production'

services:
  backend:
    container_name: tsuna-streaming-backend
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile

    command: sh docker/production/commands/setup.sh
    restart: on-failure
    env_file:
      - .env.prod

    ports:
      - "8000:8000"

    volumes:
      - .:/backend
      - .env.prod:/backend/.env

    environment:
      *COMMON_VARS
    
    depends_on:
      - postgres
      - redis
      - smtp4dev
      - celery
      - celery-beat
      - flower

  postgres:
    image: postgres:11

    container_name: tsuna-streaming-database
    restart: on-failure

    ports: 
          - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  test_postgres:
    image: postgres:11

    container_name: tsuna-streaming-test-database
    restart: on-failure

    ports:
          - "5433:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: tsuna-streaming-pgadmin
      restart: on-failure

      environment:
          - PGADMIN_DEFAULT_EMAIL=test@test.com
          - PGADMIN_DEFAULT_PASSWORD=test
      ports:
          - "5050:80"

      volumes: 
          - /data/pgadmin:/var/lib/pgadmin/data
    
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: tsuna-streaming-smtp4dev

    ports:
      - "5000:80"
      - "25:25"
      
    restart: always

  redis:
    image: redis:6.2-alpine
    container_name: tsuna-streaming-redis
    
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env.prod

  celery:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile

    container_name: tsuna-streaming-celery
    command: sh docker/production/commands/celery.sh
    depends_on:
      - redis
    volumes:
      - .:/backend
    environment:
      *COMMON_VARS
    env_file:
      - .env.prod

  celery-beat:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    container_name: tsuna-streaming-celery-beat
    command: sh docker/production/commands/celery-beat.sh
    depends_on:
      - redis
    volumes:
      - .:/backend
    environment:
      *COMMON_VARS
    env_file:
      - .env.prod

  flower:

    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    command: sh docker/production/commands/flower.sh

    depends_on:
      - redis
      - celery
    volumes:
      - .:/backend
    ports:
      - "5555:5555"
    env_file:
      - .env.prod

    environment:
      *COMMON_VARS

networks:
  main:

volumes:
  postgres-data: