version: '3.9'

x-environment: &COMMON_VARS
    DJANGO_SETTINGS_MODULE: 'config.settings.local'
    ENVIRONMENT: LOCAL

services:

  backend:
    container_name: tsuna-streaming-backend
    command: sh ./docker/commands/setup.sh
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    env_file:
      - backend/.env.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/.env.local:/backend/.env
    environment:
      *COMMON_VARS
    depends_on:
      postgres: 
        condition: service_healthy
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started

  postgres:
    image: postgres:11
    container_name: tsuna-streaming-database
    restart: on-failure
    env_file:
      - backend/.env.local
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  test_postgres:
    image: postgres:11
    container_name: tsuna-streaming-test-database
    restart: on-failure
    env_file:
      - backend/.env.local
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tsuna-streaming-pgadmin
    restart: on-failure
    env_file:
      - backend/.env.local
    ports:
      - "5050:80"
    volumes:
      - /data/pgadmin:/var/lib/pgadmin/data

  redis:
    image: redis:6.2-alpine
    container_name: tsuna-streaming-redis
    restart: always
    expose:
      - "6379"
    volumes:
        - redis-data:/data

  test_redis:
    image: redis:6.2-alpine
    container_name: tsuna-streaming-test-redis
    restart: always
    expose:
      - "6379"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: tsuna-streaming-smtp4dev
    ports:
      - "5000:80"
    expose:
      - "80"
    restart: always

  celery:
    container_name: tsuna-streaming-celery
    command: sh ./docker/commands/celery.sh
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env.local
    environment:
      *COMMON_VARS
    depends_on:
      - backend

  celery-beat:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile
    container_name: tsuna-streaming-celery-beat
    command: sh ./docker/commands/celery-beat.sh
    volumes:
      - ./backend:/backend
    env_file:
        - backend/.env.local
    environment:
      *COMMON_VARS
    depends_on:
      - backend

  flower:
    container_name: tsuna-streaming-flower
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    command: sh ./docker/commands/flower.sh
    env_file:
      - backend/.env.local
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/backend
    environment:
      *COMMON_VARS
    depends_on:
      - backend

  # frontend:
  #   extends:
  #     file: frontend/docker-compose.yml
  #     service: frontend

volumes:
  postgres-data:
  redis-data: