version: '3.9'

services:

  backend:
    extends:
      file: backend/docker-compose.prod.yml
      service: backend
    depends_on:
      - postgres
      - redis
      - smtp4dev

  postgres:
    extends:
      file: backend/docker-compose.prod.yml
      service: postgres

  test_postgres:
    extends:
      file: backend/docker-compose.prod.yml
      service: test_postgres

  pgadmin:
    extends:
      file: backend/docker-compose.prod.yml
      service: pgadmin

  redis:
    extends:
      file: backend/docker-compose.prod.yml
      service: redis


  smtp4dev:
    extends:
      file: backend/docker-compose.prod.yml
      service: smtp4dev

  celery:
    extends:
      file: backend/docker-compose.prod.yml
      service: celery
    depends_on:
      - redis
      - backend

  celery-beat:
    extends:
      file: backend/docker-compose.prod.yml
      service: celery-beat
    depends_on:
      - redis
      - backend

  flower:
    extends:
      file: backend/docker-compose.prod.yml
      service: flower
    depends_on:
      - redis
      - celery
      - backend


  # frontend:
  #   extends:
  #     file: frontend/docker-compose.prod.yml
  #     service: frontend

volumes:
  postgres-data: