version: '3.9'

services:

  backend:

    build: .
    command: sh setup-dev.sh


    container_name: backend
    restart: on-failure

    ports:
      - 8000:8000

    volumes:
      - .:/backend

    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    
    depends_on:
      - db
      - redis

  db:
    image: postgres:11

    container_name: database
    restart: on-failure

    ports: 
          - "5432:5432"
    volumes:
            - /var/lib/docker/basedata:/var/lib/postgresql/data
          
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  smtp4dev:
    image: rnwood/smtp4dev:v3

    ports:
      - 5000:80
      - 25:25
      
    restart: always

  redis:
    image: redis:6.2-alpine
    
    ports:
      - 6379:6379

    restart: always


  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/backend