version: '3.9'

x-environment: &COMMON_VARS
    DJANGO_SETTINGS_MODULE: 'config.settings.local'

services:
  backend:
    container_name: tsuna-streaming-backend
    command: sh docker/local/commands/setup.sh
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
      - .env.local:/backend/.env
    environment:
      *COMMON_VARS

  postgres:
    image: postgres:11
    container_name: tsuna-streaming-database
    restart: on-failure
    env_file:
      - .env.local
    ports: 
          - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test_postgres:
    image: postgres:11
    container_name: tsuna-streaming-test-database
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - "5433:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: tsuna-streaming-pgadmin
      restart: on-failure
      environment:
          - PGADMIN_DEFAULT_EMAIL=test@test.com
          - PGADMIN_DEFAULT_PASSWORD=test
      ports:
          - "5050:80"
      volumes: 
          - /data/pgadmin:/var/lib/pgadmin/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: tsuna-streaming-smtp4dev
    ports:
      - "5000:80"
      - "25:25"
    restart: always

  redis:
    image: redis:6.2-alpine
    container_name: tsuna-streaming-redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    container_name: tsuna-streaming-celery
    command: sh docker/local/commands/celery.sh
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - .:/backend
    env_file:
      - .env.local
    environment:
      *COMMON_VARS

  celery-beat:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: tsuna-streaming-celery-beat
    command: sh docker/local/commands/celery-beat.sh
    volumes:
      - .:/backend
    env_file:
      - .env.local
    environment:
      *COMMON_VARS

  flower:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: sh docker/local/commands/flower.sh
    env_file:
      - .env.local
    ports:
      - "5555:5555"
    volumes:
      - .:/backend
    environment:
      *COMMON_VARS

volumes:
  postgres-data:
