# Generated by Django 4.1.4 on 2023-02-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('channel_admins', '0002_alter_admin_promoted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('add_object', models.BooleanField(default=False)),
                ('edit_object', models.BooleanField(default=False)),
                ('delete_object', models.BooleanField(default=False)),
                ('publish_object', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='channel_admins.admin')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('admin', 'model'), name='unique_admin_model'),
        ),
    ]
