# Generated by Django 4.1.4 on 2023-03-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0005_alter_permission_delete_object_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='channel_admins.admin'),
        ),
    ]
