# Generated by Django 4.1.4 on 2023-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0008_alter_channeladmin_promoted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladmin',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='channeladminpermission',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
