apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsuna-streaming-celery-deployment
  namespace: default

spec:
  replicas: 1
  selector:
      matchLabels:
        app: tsuna-streaming-celery

  template:
    metadata:
        labels:
            app: tsuna-streaming-celery
    spec:
      containers:
        - name: celery
          image: ml06py/tsuna_streaming
          command: ["/bin/sh"]
          args: ["/backend/docker/commands/celery.sh"]

          envFrom:
            - configMapRef:
                name: tsuna-streaming-env

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.local"
            - name: ENVIRONMENT
              value: "LOCAL"

        - name: celery-beat
          image: ml06py/tsuna_streaming
          command: ["/bin/sh"]
          args: ["/backend/docker/commands/celery-beat.sh"]

          envFrom:
            - configMapRef:
                name: tsuna-streaming-env

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.local"
            - name: ENVIRONMENT
              value: "LOCAL"

