# Generated by Django 4.1.4 on 2023-02-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, related_name='promoted_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
