# Generated by Django 4.1.4 on 2023-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_permission_permission_unique_admin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='delete_object_comment',
            field=models.BooleanField(default=True),
        ),
    ]
