# Generated by Django 4.1.4 on 2023-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_permission_delete_object_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='delete_object_comment',
            field=models.BooleanField(default=False),
        ),
    ]
