apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev-deployment
  labels:
    app: tsuna-streaming-smtp4dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsuna-streaming-smtp4dev
  template:
    metadata:
      labels:
        app: tsuna-streaming-smtp4dev
    spec:
      containers:
        - name: smtp
          image: rnwood/smtp4dev:v3
