# Generated by Django 4.1.4 on 2023-01-27 09:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='token',
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
    ]
