# Generated by Django 4.1.4 on 2023-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_video_allow_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                default="assets/images/default-video-thumbnail.jpg",
                upload_to="videos/thumbnail/",
            ),
        ),
    ]
