version: '3.9'

x-environment: &DJANGO_SETTINGS_MODULE
    DJANGO_SETTINGS_MODULE: 'config.settings.local'

services:

  backend:

    build:
      context: ../../
      dockerfile: ./docker/local/Dockerfile

    command: sh docker/local/setup.local.sh

    container_name: tsuna-streaming-backend
    restart: on-failure

    ports:
      - 8000:8000

    volumes:
      - .:/backend

    environment:
      *DJANGO_SETTINGS_MODULE
    
    depends_on:
      - db
      - redis

  db:
    image: postgres:11

    container_name: tsuna-streaming-database
    restart: on-failure

    ports: 
          - "5432:5432"
    volumes:
            - /var/lib/docker/basedata:/var/lib/postgresql/data
          
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  pgadmin:
      image: dpage/pgadmin4
      container_name: tsuna-streaming-pgadmin
      restart: on-failure

      environment:
          - PGADMIN_DEFAULT_EMAIL=test@test.com
          - PGADMIN_DEFAULT_PASSWORD=test
      ports:
          - "5050:80"

      volumes: 
          - /data/pgadmin:/var/lib/pgadmin/data
    
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: tsuna-streaming-smtp4dev

    ports:
      - 5000:80
      - 25:25
      
    restart: always

  redis:
    image: redis:6.2-alpine
    container_name: tsuna-streaming-redis
    
    ports:
      - 6379:6379

    restart: always

  celery:
    build: .
    container_name: tsuna-streaming-celery
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/backend
    environment:
      *DJANGO_SETTINGS_MODULE

  celery-beat:
    build: .
    container_name: tsuna-streaming-celery-beat
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/backend
    environment:
      *DJANGO_SETTINGS_MODULE

  flower:

    build: .
    command: celery -A config flower

    depends_on:
      - backend
      - redis
      - celery

    ports:
      - 5555:5555

    environment:
      *DJANGO_SETTINGS_MODULE