# Generated by Django 4.1.4 on 2023-07-15 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0009_alter_channeladmin_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladmin',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='channeladminpermission',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
