# Generated by Django 4.1.4 on 2023-07-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0010_alter_channeladmin_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeladmin',
            name='add_new_admin',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='block_user',
        ),
        migrations.RemoveField(
            model_name='channeladmin',
            name='change_channel_info',
        ),
        migrations.RemoveField(
            model_name='channeladminpermission',
            name='delete_object_comment',
        ),
        migrations.RemoveField(
            model_name='channeladminpermission',
            name='model',
        ),
    ]
