# Generated by Django 4.1.4 on 2023-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0014_channeladminpermission_user'),
    ]

