# Generated by Django 4.1.4 on 2023-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0018_alter_channeladminpermission_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeladminpermission',
            old_name='add_object',
            new_name='can_add_object',
        ),
        migrations.RemoveField(
            model_name='channeladminpermission',
            name='delete_object',
        ),
        migrations.RemoveField(
            model_name='channeladminpermission',
            name='edit_object',
        ),
        migrations.RemoveField(
            model_name='channeladminpermission',
            name='publish_object',
        ),
        migrations.AddField(
            model_name='channeladminpermission',
            name='can_change_channel_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channeladminpermission',
            name='can_delete_object',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channeladminpermission',
            name='can_edit_object',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channeladminpermission',
            name='can_publish_object',
            field=models.BooleanField(default=False),
        ),
    ]
