# Generated by Django 4.1.4 on 2023-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
