# Generated by Django 4.1.4 on 2023-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0007_channelsubscriber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channeladmin",
            name="block_user",
            field=models.BooleanField(default=False),
        ),
    ]
