# Generated by Django 4.1.4 on 2023-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0009_alter_channel_profile_alter_channel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="channeladmin",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
