# Generated by Django 4.1.4 on 2023-02-28 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0013_alter_channeladmin_channel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelAdmin",
        ),
    ]
