# Generated by Django 4.1.4 on 2023-07-28 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0019_rename_profile_channel_avatar_and_more"),
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vote",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
