apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
    selector:
        app: tsuna-streaming-backend
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
    type: LoadBalancer
