name: Test On Kubernetes
description: "Test the application on kubernetes"

runs:
  using: 'composite'
  steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Create ConfigMap
      run: kubectl create configmap tsuna-streaming-env --from-env-file=./backend/.env.local && kubectl create configmap tsuna-streaming-env-file --from-file=.env=./backend/.env.local
      shell: bash

    - name: Run Kubernetes Deployments
      run: make k8s
      shell: bash

    - name: Wait for Test Database Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/tsuna-streaming-postgres-deployment
      shell: bash

    - name: Wait for Redis Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/tsuna-streaming-redis-deployment
      shell: bash

    - name: Wait for Backend Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/tsuna-streaming-backend-deployment
      shell: bash

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest
      shell: bash