# Generated by Django 4.1.4 on 2023-03-12 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('description', models.TextField(default='No Description available', max_length=400)),
                ('price', models.PositiveBigIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(10)])),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('active_months', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)])),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
