# Generated by Django 4.1.4 on 2023-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_subscription_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="finish_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
