# Generated by Django 4.1.4 on 2023-02-11 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_subscription"),
        ("accounts", "0017_alter_plan_token_alter_subscription_token_and_more"),
    ]

    operations = []
