# Generated by Django 4.1.4 on 2023-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_merge_20230211_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="token",
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="token",
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
    ]
