# Generated by Django 4.1.4 on 2023-03-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_alter_plan_token_alter_subscription_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="accounts.plan",
            ),
        ),
    ]
