# Generated by Django 4.1.4 on 2023-07-16 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_verificationtoken_delete_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
