apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsuna-streaming-redis-deployment
  labels:
      app: tsuna-streaming-redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tsuna-streaming-redis
    template:
      metadata:
        labels:
            app: tsuna-streaming-redis
        spec:
            containers:
            - name: tsuna-streaming-redis
              image: redis:6.2-alpine
              ports:
              - containerPort: 6379