apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
    selector:
        app: tsuna-streaming-redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
    type: LoadBalancer