# Generated by Django 4.1.4 on 2023-03-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('channels', '0014_delete_channeladmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel_admins', '0006_alter_permission_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('change_channel_info', models.BooleanField(default=False)),
                ('add_new_admin', models.BooleanField(default=False)),
                ('block_user', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='channels.channel')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, related_name='promoted_admin', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('add_object', models.BooleanField(default=False)),
                ('edit_object', models.BooleanField(default=False)),
                ('delete_object', models.BooleanField(default=False)),
                ('publish_object', models.BooleanField(default=False)),
                ('delete_object_comment', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='channel_admins.channeladmin')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='model',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddConstraint(
            model_name='channeladmin',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='unique_channel_admin'),
        ),
    ]
