# Generated by Django 4.1.4 on 2023-07-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0011_remove_channeladmin_add_new_admin_and_more'),
    ]
