# Generated by Django 4.1.4 on 2023-07-24 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel_admins', '0013_channeladminpermission_unique_admin_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladminpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
