# Generated by Django 4.1.4 on 2023-07-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0016_remove_channeladminpermission_unique_admin_permission_and_more'),
    ]