# Generated by Django 4.1.4 on 2023-07-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel_admins', '0017_remove_channeladminpermission_unique_admin_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladminpermission',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='channel_admins.channeladmin'),
        ),
    ]
