# Generated by Django 4.1.4 on 2023-02-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_is_verified'),
        ('channels', '0010_alter_channel_token_alter_channeladmin_token'),
    ]

    operations = [
    ]
