# Generated by Django 4.1.4 on 2023-07-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0018_alter_channel_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='profile',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
