# Generated by Django 4.1.4 on 2023-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
