# Generated by Django 4.1.4 on 2023-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
