apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
      app: tsuna-streaming-postgres

spec:
  selector:
    app: tsuna-streaming-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432